### ISSUE TITLE
Proxy config not applied when installed in SHC

### ISSUE THREAD

**Issue by doksu** [doksu/TA-centralops#5]
Search head cluster (SHC) deployers merge/flatten app configs into the app's 'default' folder before pushing to cluster nodes. The centralopswhois.py script only looks in the 'local' folder for proxy config (because the default config is empty) and so can't "see" the proxy config when a deployer flatens and pushes to cluster nodes.

**Comment by doksu** [comment]
Version 1.2.0 published on Splunkbase (https://splunkbase.splunk.com/app/3506/) fixes this issue and provides Python 3 support for Splunk 8+

**Comment by sklatheefp123-web** [comment]
Hello
we are facing "/opt/splunk/etc/apps/TA-centralops/bin/centralopswhois.py", line 156 : Failed to connect to centralops.net - please check TA-centralops app proxy settings issue in Splunk Enterprise 9.4, same error regarding proxy, can you please assist. Also, is there any new version in pipeline for Splunk Enterprise version 10?
